export const ERROR_CODES = {
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  PROFILE_UPDATE_EMPTY: "PROFILE_UPDATE_EMPTY",
  PROFILE_AVATAR_INVALID_CONTENT_TYPE: "PROFILE_AVATAR_INVALID_CONTENT_TYPE",
  NEWS_POST_NOT_FOUND: "NEWS_POST_NOT_FOUND",
  QUIZ_NOT_FOUND: "QUIZ_NOT_FOUND",
  QUIZ_QUESTION_NOT_FOUND: "QUIZ_QUESTION_NOT_FOUND",
  QUIZ_ANSWER_NOT_FOUND: "QUIZ_ANSWER_NOT_FOUND",
  QUIZ_QUESTION_ALREADY_ANSWERED: "QUIZ_QUESTION_ALREADY_ANSWERED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;
